#+TITLE: Mohammed Albatati Resume
#+DESCRIPTION: My online resume
#+OPTIONS: toc:nil

* General Information
| Name            | Mohammed Salah Albatati |
|-----------------+-------------------------|
| Nationally      | Yemeni                  |
| Occupation      | Service Deliver Manager |
| Birthday        | 03 Aug 1981             |
| Current Address | Iraq - Erbil            |
| Mail 1          | mohalatati@icloud.com   |
| Mail 2          | mohalatati@hotmail.com  |

* Education
Bachelor Degree Majored in Chemical engineering and performed a graduation project of designing a plant to sweet a sour LNG using Di-ethanol Glycol in a absorption column in 2004.

* Carrier Information
| Company              | Duration            | Last Position              | Operation           | Duration |
|----------------------+---------------------+----------------------------+---------------------+----------|
| OilSERV - Iraq       | Jan 2017 - Now      | Service Delivery Manager   | Testing & Slickline | 5 Y      |
| OilSERV - Iraq       | Jan 2015 - Feb 2017 | Service Quality Coach      | Testing             | 2 Y      |
| OilSERV - Iraq       | Apr 2013 - Dec 2014 | Testing Engineer In Charge | Testing             | 2 Y      |
| OMV Yemen            | Jul 2010 - Apr 2013 | Field Production Engineer  | Production          | 3 Y      |
| Schlumberger - Yemen | Mar 2006 - Jul 2010 | Senior Field Engineer      | Testing             | 4 Y      |

* Overall Summary
- Currently taking the role of Service delivery manager and acting as operation manager for 8 Testing units and 4 slickline units with a team of 140 crew members employees and consultants, and responsible for the availability of operational equipment’s & competent personnel for our client (DNO, HKN, TAQA, Rosneft & Gazprom), also responsible for the review the monthly PnL.

- Also worked as Service Quality Coach for the Surface well test & slick line crew ensuring correct execution of best service quality service to our client also in charge of generating service operating procedures SOP in addition to conduct technical training for the crew to on EPICOR software for maintenance services entry.

- From 2013 Jun to Dec 2014 was acting as Service delivery manager while keeping my position as Testing Engineer In charge, maintaining and running 8 surface Testing packages with around 85 personnel on board consist of supervisors, chief operators, Data Engineers, Operators and mechanics, making sure all equipment are well maintained for upcoming jobs and select competent crew for each job along with giving full support for ongoing Operation. Conducting field and base audits, reviewing and presenting incident reports to top management on monthly bases, meeting with clients and make packages design and solutions for client requests for Oil production and Testing. Responsible for crew planning in/out the field while maintaining good Relationship with the team, making plan for the equipment Maintenance and certification documentation by implementing my own project of QR code with SharePoint integration.

- Worked in OMV Yemen as Field Production Engineer since July 2010, responsible in intervention operation for rig and rig-less sites such as Slick line operation supervision, down hole memory gauges setup and programming, PLT & FSI (CoilTubing & Wire Line) program preparation and execution, Optimization of Wells Production in the Block S2 OMV and Completion Natural & ESP installation program preparation and execution.

- Also responsible for running SUBPUMP software to analyze the runing ESP wells to meet its designed operating conditions. Also, have the responsibility to update Habban field in model in GAP/PROSPER software every quarter in a workshop meeting. Furthermore, have experience in running PANSYS software to obtain reservoir characterization.

- At Schlumberger Joined as junior field engineer and leaved the company as senior field testing engineer after getting specialized in Surface well testing & down hole data acquisition and multiphase engineer.

* Overall Carrier Experience:
1. Well Testing & Data Acquisition
2. Production Technology
3. Multi Phase Metering Technology

* Overall Skills:
1. MS Access database
2. Website creating with framework:

   a. Django
   b. Reat

3. AutoCad 2d for P&ID
4. Programming Language:

   a. Python
   b. JavaScript

* Certificate Acquired:

| Certificate               | Location         | Year  |
|---------------------------+------------------+-------|
| SDM Course                | UAE _ Duabi      | 2019  |
| Artifical Lift Technology | Austria _ Vienna | 2013  |
| Well Contol BOP Stack     | Malaysia _ KL    | 2012  |
| ESP Application           | UAE _ Duabi      | 2011  |
| GAP/PROSPER/MBAL          | Yemen _ Sana     | 2010  |
| People Management         | UAE _ Dubai      | 2010  |
| VX Multi Phase Metering   | France _ Paris   | 2008  |
| SWT / TDA                 | France _ Paris   | 2006  |

* Self-Initiated Project:
1) At Schlumberger Created a Database software to track and trace all the equipment certification and generate reports for the upcoming equipment need maintenance.
2) At OMV Yemen created a database management system with access 2010 which have a one universal window that shows all the information for each well in Habban Field and having all its files attached along with the activities performed/ failure log etc. and can be accessed from the field and Town by using the frontend-backend feature in the access while the Main ACCESS file is stored safely in OMV field server.
3) Designed a web site for OMV Yemen Habban field using ADOBE Dreamweaver CS5 which contains all the wells and shows a production trend for the whole field along with production rates and statistics for each well, the web site were installed in OMV local server and can be accessed if the used was connected to that server and was not accessed through internet for safety of information.
4) At OMV Yemen created a Database with ACCESS 2010 to track the Diesel consumption of each vehicle used in Habban field along with calculating the remaining diesel in the tanks and generate monthly reports of the consumption of each vehicle.
5) At OMV Yemen Once the IT announced the implementation of SharePoint in OMV made the request and created a SharePoint site and called it HabbanFieldSite and implemented all the web site design and information in it (https://2connect-at.omv.com/teams/habbanonline/SitePages/Welcome to OMV Yemen.aspx ), this site is only accessed by OMV employee’s and is being used by the teams in Block S2 Habban Field, Sanaa Office & Dubai Office. All these self-projects were acknowledged by OMV field Manager and Ops Managers in Dubai and I received a mail of appreciation.
6) At OilSERV Iraq, created a Surface well testing page in SharePoint and created a document library for all the equipment available in the location which each item is grouped by Type/Serial Number, which made all the equipment information available on line. Also enforced all the supervisors to sync their laptops with the SharePoint site so all personnel are updated with the new files and certification.
7) At OilSERV Iraq, Integrated SharePoint library with QR code which I created a QR label linking the equipment folder and made the laminated labels for each equipment. Using your smart phone you can scan the label on the equipment will take you straight to its folder and can access all the files for that item. This system was acknowledged by OilSERV VP and CEO and the company is working to implement the process to all other business lines.
8) At OilSERV Started a tutorial online training for the crew using screen flow software and upload the tutorial videos to OilSERV video portal for all locations to access it anytime and help them use EPICOR maintenance software on the go.
9) At OiLSERV created a database using Access 2013 that capture all the equipment available in the fixed asset and can update every single maintenance record and track the asset history with an easy to generator reports.
10) At OiLSERV created the same as above but using python & Django
